ddelange/pipgrip

README.md, src/pipgrip/cli.py, src/pipgrip/libs/mixology/constraint.py, src/pipgrip/libs/mixology/package.py, src/pipgrip/libs/mixology/term.py, src/pipgrip/libs/mixology/version_solver.py, src/pipgrip/package_source.py, src/pipgrip/pipper.py, tests/test_cli.py, tests/tests_mixology/package_source.py
=> :recycle: Add support for extras_require

src/pipgrip/pipper.py
This allows me to install `jupyterlab-black`.
Closes #20
=> :bug: Handle packages with hyphens for older pip versions

README.md, src/pipgrip/cli.py, src/pipgrip/pipper.py
This allows passing `--user` to `pip install`:
```
$ pipgrip --verbose --install --user jupyterlab-black
jupyterlab-black==0.2.1
[...]
Installing collected packages: attrs, backcall, bleach, decorator, zipp, importlib-metadata, ipython-genutils, traitlets, tornado, wcwidth, prompt-toolkit, pexpect, parso, jedi, pygments, setuptools, pickleshare, ipython, ipykernel, jinja2, mistune, nbformat, pandocfilters, prometheus-client, pyparsing, python-dateutil, pyzmq, send2trash, terminado, testpath
Successfully installed attrs-19.3.0 backcall-0.2.0 bleach-3.1.5 decorator-4.4.2 importlib-metadata-1.7.0 ipykernel-5.3.0 ipython-7.16.1 ipython-genutils-0.2.0 jedi-0.17.1 jinja2-2.11.2 mistune-0.8.4 nbformat-5.0.7 pandocfilters-1.4.2 parso-0.7.0 pexpect-4.8.0 pickleshare-0.7.5 prometheus-client-0.8.0 …
```
=> :sparkles: Add --user option

src/pipgrip/libs/semver/__init__.py, tests/tests_semver/test_main.py
So turns out `pipgrip.libs.semver` wasn't propagating all parsed `Version` attributes to the low end of the `Range`, so info about `prerelease` got lost. This was an interesting traceback, as I had convinced myself the culprit lived somewhere in `pipgrip.package_source` 😄 
Old behaviour:
```pycon
>>> from pipgrip.libs.semver import parse_single_constraint, Version
>>>
>>> version: Version = parse_single_constraint('~=7.0.0rc1')
>>> version.min
<Version 7.0.0>
```
New behaviour:
```pycon
>>> from pipgrip.libs.semver import parse_single_constraint, Version
>>>
>>> version: Version = parse_single_constraint('~=7.0.0rc1')
>>> version.min
<Version 7.0.0rc1>
```
Fixes #33
=> :bug: Fix libs.semver for compatible prerelease clause (~=7.0.0rc1)

requirements/prod.txt, src/pipgrip/pipper.py, tests/test_cli.py
Fixes #42 
- New resolver doesn't output available versions anymore (could do parsing of the new `-v` output as alternative to this fix)
- Legacy resolver will be deprecated in pip 21 (ref https://github.com/pypa/pip/issues/9187#issuecomment-736000492), so pre-emptively dropping support
=> :ambulance: Get available versions using legacy resolver in pip~=20.3

src/pipgrip/pipper.py
Running `pipgrip -vv` with a lot of root dependencies (big requirements file or so), would result in a long silence (where pipgrip is discovering dependencies for all the root dependencies). This logger makes that apparent.
=> Add info logger (although not strictly a solving decision)

src/pipgrip/cli.py
Properly extract the package name from the error message containing a version: `aliyun-python-sdk-core-v3==2.13.31` ref #77 
```
$ pipgrip knack oss2
ERROR: Downloading/building wheel for aliyun-python-sdk-core-v3==2.13.31 failed with output:
Collecting aliyun-python-sdk-core-v3==2.13.31
Using cached aliyun-python-sdk-core-v3-2.13.31.tar.gz (440 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
WARNING: Generating metadata for package aliyun-python-sdk-core-v3 produced metadata for project name aliyun-python-sdk-core. Fix your #egg=aliyun-python-sdk-core-v3 fragments.
Discarding https://files.pythonhosted.org/packages/13/63/52c2fc00ce2334cef2051548215ae27878b187b819f01876539608752837/aliyun-python-sdk-core-v3-2.13.31.tar.gz#sha256=427f27f …
```
=> :bug: Fix partial tree rendering

src/pipgrip/libs/mixology/range.py, src/pipgrip/libs/mixology/term.py, src/pipgrip/libs/semver/version.py, tests/test_cli.py
`pipgrip requests>=2.22.0 requests@git+https://github.com/psf/requests`
used to finish successfully, now it conflicts (as pip does)
=> :bug: Disallow open ranges combined with vcs

README.md, src/pipgrip/cli.py
Thanks for the great tool, love it so far 😄 please keep it up and running 🚀 
Adjusted the help text to reflect the correct name of the `--tree-json-exact` flag.
=> :pencil2: Fix help text for --tree-json-exact flag

README.md, src/pipgrip/cli.py
Found via these commands:
codespell -L iterm
markdownlint README.md --disable MD013 MD001
=> :pencil2: Fix typos and markdowns

src/pipgrip/cli.py, src/pipgrip/libs/mixology/constraint.py, src/pipgrip/libs/mixology/package.py, src/pipgrip/libs/mixology/partial_solution.py, src/pipgrip/libs/mixology/term.py, src/pipgrip/libs/mixology/version_solver.py, tests/test_cli.py
Fixes #96 
These used to fail:
```console
$ pipgrip --tree --max-depth=2 smart-open[azure]~=6.0 smart-open[s3]==6.1.0
smart-open[azure]~=6.0 (6.1.0)
├── azure-common (1.1.28)
├── azure-core (1.25.1)
└── azure-storage-blob (12.13.1)
smart-open[s3]==6.1.0 (6.1.0)
└── boto3 (1.24.66)
$ pipgrip --tree --max-depth=3 smart-open~=6.0 pypicloud[azure-blob]~=1.3.9
smart-open~=6.0 (6.1.0)
pypicloud[azure-blob]~=1.3.9 (1.3.10)
├── smart-open[azure]>=6.1.0 (6.1.0)
│   ├── azure-common (1.1.28)
│   ├── azure-core (1.25.1)
│   └── azure-storage-blob (12.13.1)
├── smart-open[http,s3] (6.1.0)
│   ├── boto3 (1.24.66)
│   └── requests (2.28.1)
...
```
=> :bug: Fix handling of unions of package extras

README.md, src/pipgrip/cli.py, src/pipgrip/libs/mixology/version_solver.py
When multiple packages were added to `unsatisfied`, they can all be discovered using pip in parallel. This results in a substantial speed-up in certain cases.
=> :zap: Speed up using concurrent pip subprocesses

src/pipgrip/cli.py
Empirically tested on a realistic scenario using Github CI (1physical/2logical core machibe), this turned out to be a sensible default:
- 2 threads 5:30
- 4 threads 3:30
- 8 threads 2:30
- 16 threads 2:30
=> :zap: Use more threads by default

src/pipgrip/cli.py, src/pipgrip/libs/mixology/partial_solution.py, src/pipgrip/libs/mixology/range.py, src/pipgrip/libs/mixology/version_solver.py, src/pipgrip/package_source.py, src/pipgrip/pipper.py
using `py-spy` flamegraphs
also contains a bugfix based on `pipgrip -vv --tree kserve==0.10.0rc1 mxnet==1.9.1 autogluon-text==0.6.1 'aiobotocore[awscli]<=2.2.0' aioboto3`
=> :zap: Improve performance based on profiling

src/pipgrip/libs/mixology/partial_solution.py
found via `pipgrip -vv --tree kserve==0.10.0rc1 mxnet==1.9.1 autogluon-text==0.6.1 'aiobotocore[awscli]<=2.2.0' aioboto3`
would cause an infinite loop of
```
INFO: derived: aiobotocore[boto3] (==2.4.1)
INFO: derived: aiobotocore[awscli] (<=2.2.0)
```
instead of recognizing this is illegal. now it correctly starts searching versions of `aiobotocore[awscli,boto3]`
=> :bug: Fix a rare case of infinite loop related to extras

.github/workflows/main.yml, src/pipgrip/pipper.py, tests/test_cli.py, tests/test_pipper.py
With a lot of excitement, adding support for pip's new --dry-run --report functionality.
Current pip (23.2.1) will still unnecessarily build the wheel when there's metadata available. This will be fixed hopefully soon ref https://github.com/pypa/pip/pull/12186#issuecomment-1671050968.
That PR will bring the full speed-up of not having to build/download wheels anymore for wheels uploaded to PyPI after the [relevant](https://github.com/pypi/warehouse/issues/8254#issuecomment-1544557695) changes were deployed on warehouse side (~2023.06):
Closes https://github.com/ddelange/pipgrip/issues/40 🎉
Try it out now:
```
$ pip install 'pip @ https://github.com/cosmicexplorer/pip/archive/refs/heads/metadata_only_resolve_no_whl.zip'
$ pipgrip tensorflow
```
=> :zap: Prepare for metadata-only resolves

.github/dependabot.yml
CI is currently throwing deprecation warnings due to old action versions ([recent example](https://github.com/ddelange/pipgrip/actions/runs/6690468989)). For example, `actions/checkout@v2` needs to be upgraded.
Rather than updating the versions once, this PR introduces a Dependabot config to autoupdate actions each month via a PR (if any updates exist).
Note that if this PR merges, Dependabot will immediately submit a PR to update the actions.
=> :construction_worker: Add Dependabot config to autoupdate GitHub action versions

.pre-commit-config.yaml
This PR introduces the following:
* Update `isort` and `blacken-docs` URLs because their repos are now redirects
* Update `black` URL to use the mypyc-compiled version which is ~2x faster ([doc reference](https://black.readthedocs.io/en/stable/integrations/source_version_control.html))
* Run `pre-commit autoupdate` and `upadup` to update hook and `additional_dependencies` versions
After the changes, `pre-commit run -a` reported no new issues found in the codebase.
=> Update pre-commit URLs and hook/`additional_dependencies` versions

.github/workflows/main.yml, .pre-commit-config.yaml
This PR introduces the following:
* Add a pre-commit hook to validate the Dependabot config and GitHub workflow files match schema definitions
* Fix a schema issue in the `main.yml` file (`branches` must be an array of strings).
=> :construction_worker: Lint GitHub workflows and dependabot yamls

.gitignore
This addresses a significant number of unignored files generated by running pytest locally.
So far, I've been unable to run pipgrip on Windows (it crashes for multiple reasons), so I'm working to resolve an existing test suite failure before attempting to resolve the crashes I'm seeing.
=> :see_no_evil: git-ignore common Python development files

.github/workflows/main.yml, src/pipgrip/cli.py, src/pipgrip/pipper.py
Windows doesn't consistently use UTF-8 as the default system encoding.
Enabling universal newlines causes Python to decode STDOUT using the default system encoding, which may not be UTF-8 compatible. (On my PC, running Windows 10 Home, the default encoding is `cp1252`.) In addition, when pip is executed via `subprocess`, it may crash when attempting to write output containing Unicode characters.
To resolve these issues, Python's UTF-8 mode (available in 3.7+) is enabled via an environment variable, universal newlines are disabled, and STDOUT is read and explicitly decoded as UTF-8.
No new test cases are introduced, but I'm now able to successfully run pipgrip on Windows.
=> :children_crossing: Improve support for Windows

.github/workflows/main.yml, src/pipgrip/cli.py
ref https://github.com/ddelange/pipgrip/pull/128#issuecomment-1809586931
cc @kurtmckee
=> :children_crossing: Support Python UTF-8 mode on Windows

src/pipgrip/pipper.py, tests/test_pipper.py
Somehow Google Colab is forcing colored report output, and even adding `--no-color` isn't disabling it. Switching to temp file to make pipgrip robust to this config.
The ANSI escapes result in:
```pytb
Traceback (most recent call last):
File "/usr/local/bin/pipgrip", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
File …
```
=> :bug: Fix package reports on Google Colab

src/pipgrip/libs/mixology/range.py, tests/tests_mixology/test_basic_graph.py, tests/tests_mixology/test_unsolvable.py
Before this change, `pipgrip --pre 'django<5.0'` would select django==5.0rc1 (because that is technically a version that comes before 5.0), whereas `pip install --pre 'django<5.0'` will select django==4.2.11. This PR fixes behaviour parity with pip.
=> :bug: Exclude 5.0rc1 when <5 is requested

src/pipgrip/cli.py, src/pipgrip/pipper.py, tests/test_cli.py
#113 indroduced `--dry-run --report` which broke the logic here to show a partial best guess tree on failures.
=> :children_crossing: Show partial solution on build errors
